name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Set this to your default branch, e.g., main or master
  pull_request:
    branches:
      - main  # Set this to your default branch, e.g., main or master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/mumax3-python-env:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
